'use strict';

const express = require('express');
const router = express.Router();
const db = require('../db');

// ==========================================
// CTO SECURITY: TENANT EXTRACTION MIDDLEWARE
// ==========================================
const extractTenant = (req, res, next) => {
  const authHeader = req.headers.authorization;
  let academyId = 'DEMO_ACADEMY'; // Safe fallback
  
  if (authHeader && authHeader.startsWith('Bearer ')) {
    const token = authHeader.split(' ')[1];
    // We parse the token generated by our Smart Router in server.js
    if (token.startsWith('swpi-token-')) {
      academyId = token.replace('swpi-token-', '');
    }
  }
  
  req.academyId = academyId;
  next();
};

// Apply middleware to all routes in this file
router.use(extractTenant);

// 🔥 GET ALL PLAYERS (Strictly filtered by Academy ID)
router.get('/', async (req, res) => {
  try {
    let result;
    
    // Super Admin sees everything
    if (req.academyId === 'ALL') {
      result = await db.query(`SELECT * FROM players ORDER BY name ASC`);
    } else {
      // Coaches only see their academy
      result = await db.query(
        `SELECT * FROM players WHERE academy_id = $1 ORDER BY name ASC`, 
        [req.academyId]
      );
    }

    res.json(result.rows);
  } catch (error) {
    console.error('[playerRoutes] Error fetching players:', error.message);
    res.json([]);
  }
});

// 🔥 GET SINGLE PLAYER (Secured)
router.get('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    let result;

    if (req.academyId === 'ALL') {
      result = await db.query('SELECT * FROM players WHERE id = $1', [id]);
    } else {
      result = await db.query('SELECT * FROM players WHERE id = $1 AND academy_id = $2', [id, req.academyId]);
    }
    
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Player not found or access denied.' });
    }

    res.json(result.rows[0]);
  } catch (error) {
    console.error(`[playerRoutes] Error fetching player ${req.params.id}:`, error.message);
    res.status(500).json({ error: 'Failed to fetch player details' });
  }
});

// 🔥 QUARTERLY TREND (Secured)
router.get('/:id/quarterly-trend', async (req, res) => {
  try {
    const { id } = req.params;
    let result;

    if (req.academyId === 'ALL') {
      result = await db.query(
        `SELECT quarterly_cycle as label, overall_score as score, test_date 
         FROM assessment_sessions WHERE user_id = $1 ORDER BY test_date ASC`,
        [id]
      );
    } else {
      result = await db.query(
        `SELECT quarterly_cycle as label, overall_score as score, test_date 
         FROM assessment_sessions WHERE user_id = $1 AND academy_id = $2 ORDER BY test_date ASC`,
        [id, req.academyId]
      );
    }

    res.json(result.rows.map(row => ({
      label: row.label || (row.test_date ? new Date(row.test_date).toLocaleDateString('en-GB', { month: 'short', year: '2-digit' }) : 'N/A'),
      avg_score: Math.round(Number(row.score || 0))
    })));
  } catch (error) {
    console.error(`[player-trend-q] Error for player ${req.params.id}:`, error.message);
    res.json([]);
  }
});

// 🔥 ADD PLAYER (Upgraded to handle real inserts and lock to academy)
router.post('/', async (req, res) => {
  try {
    // If Admin is adding a player, default them to Demo Academy to prevent errors
    const targetAcademy = req.academyId === 'ALL' ? 'DEMO_ACADEMY' : req.academyId;
    
    const { 
      fullName, dob, gender, role, idNo, aadhaarNo, standard, division 
    } = req.body;

    if (!fullName || !dob) {
      return res.status(400).json({ error: 'Full Name and DOB are required' });
    }

    const result = await db.query(
      `INSERT INTO players 
      (name, dob, gender, role, school_id_no, aadhaar_card_no, standard, division, academy_id, latest_score) 
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 0) 
      RETURNING *`,
      [fullName, dob, gender, role, idNo, aadhaarNo, standard, division, targetAcademy]
    );

    res.json({
      message: "Player added successfully",
      player: result.rows[0]
    });
  } catch (error) {
    console.error('[playerRoutes] Error adding player:', error.message);
    res.status(500).json({ error: 'Failed to add player to database' });
  }
});

module.exports = router;